config/routes.rb
Rails.application.routes.draw do

  put 'users/:id/approve' => 'users#approve', as: :approve
  put 'users/:id/make_admin' => 'users#make_admin', as: :make_admin
  get 'project' => 'static_pages#project', as: :project
  get 'instructions' => 'static_pages#instructions', as: :instructions
  get 'dataset/:id/download' => 'datasets#download', as: :download
  get 'dataset/download' => 'datasets#download_all', as: :download_all

  devise_for :users
  resources :datasets
  root 'static_pages#home'

end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  has_many :tweets, dependent: :destroy
  belongs_to :user

  def annotated_tweets
    self.tweets.where.not(annotation: nil)
  end

  def get_unannotated_tweet
    self.tweets.shuffle.each do |t|
      return t if t.annotation == nil
    end
    return nil
  end

  def progress
    self.annotated_tweets.size * 100 / self.tweets.size
  end

  def to_csv
    csv_text = ''
    self.annotated_tweets.each do |tweet|
      csv_text << "#{tweet.twitter_id};#{tweet.text};#{tweet.annotation}\n"
    end
    csv_text
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :dataset
  validates_inclusion_of :annotation, :in => [0, 1, 2, nil], on: :update

  def readable_annotation
    case self.annotation
    when 0
      return 'irrelevant'
    when 1
      return 'request'
    when 2
      return 'offer'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable
  has_many :datasets

  after_create :send_admin_mail
  def send_admin_mail
    AdminMailer.new_user_waiting_for_approval(self).deliver
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

  def annotations
    if self.datasets
      self.datasets.inject(0) {|sum, d| sum + d.annotated_tweets.size }
    else
      0
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @datasets = Dataset.all
    @total_annotated = @datasets.collect {|d| d.annotated_tweets.size}.reduce(:+)
    winner_amount = 0
    @winners = []
    User.all.each do |u|
      ann = u.annotations
      if ann > winner_amount
        winner_amount = ann
        @winners = [u.id]
      elsif ann == winner_amount
        @winners << u.id
      end
    end
  end

  def edit
    @dataset = Dataset.find(params[:id])
    # not admin
    unless current_user.has_role? :admin or current_user.email == @dataset.user.email
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end

    # dataset is done
    unless @tweet = @dataset.get_unannotated_tweet
      redirect_to dataset_path(@dataset.id)
    end
  end

  def update
    @dataset = Dataset.find(params[:id])
    unless current_user.has_role? :admin or current_user.email == @dataset.user.email
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
    @tweet = Tweet.find(params[:dataset][:tweet_id])
    @tweet.update(annotation: params[:dataset][:annotation])
    @dataset.update(updated_at: DateTime.now)
    if params[:dataset][:annotation] != ""
      redirect_to edit_dataset_path(@dataset.id)
    else
      redirect_to dataset_path(@dataset.id)
    end
  end

  def destroy
    unless current_user.has_role? :admin
      render(:file => File.join(Rails.root, 'public/403.html'), \
        :status => 403, :layout => false)
      return
    end
    @dataset = Dataset.find(params[:id])
    @dataset.destroy!
    redirect_to datasets_path
  end

  def show
    @dataset = Dataset.find(params[:id])
  end

  def download
    unless current_user.has_role? :admin
      render(:file => File.join(Rails.root, 'public/403.html'), \
        :status => 403, :layout => false)
      return
    end
    @dataset = Dataset.find(params[:id])
    time = DateTime.now.in_time_zone("Caracas").strftime('%s')
    send_data @dataset.to_csv,
      filename: "annotated_export_#{time}.csv",
      :type => 'text/csv',
      disposition: 'attachment'
  end

  def download_all
    unless current_user.has_role? :admin
      render(:file => File.join(Rails.root, 'public/403.html'), \
        :status => 403, :layout => false)
      return
    end

    time = DateTime.now.in_time_zone("Caracas").strftime('%s')
    exports = ''
    Dataset.all.each do |dataset|
      exports << dataset.to_csv
    end

    send_data exports,
      filename: "annotated_export_#{time}.csv",
      :type => 'text/csv',
      disposition: 'attachment'
  end

  def new
    unless current_user.has_role? :admin
      render(:file => File.join(Rails.root, 'public/403.html'), \
        :status => 403, :layout => false)
      return
    end
    @dataset = Dataset.new
    @available_users = User.all
  end

  def create
    unless current_user.has_role? :admin
      render(:file => File.join(Rails.root, 'public/403.html'), \
        :status => 403, :layout => false)
      return
    end
    if params[:dataset].include? :csv and params[:dataset].include? :user
      @owner = User.find_by(email: params[:dataset][:user])
      @dataset = Dataset.create!(user: @owner)

      good_text = params[:dataset][:csv].read.encode('UTF-8', 'binary', \
        invalid: :replace, undef: :replace, replace: '').gsub("u'","'")

      tweets = []

      good_text.each_line do |line|
        tweet_parsed_info = {}
        text = line.tr("\n",'').split(';').each do |item|
          key, *value = item.split(':', 2)
          tweet_parsed_info[key] = value[0] if key
        end
        tweets << tweet_parsed_info
      end
      bulk_insert_tweets(tweets)

      redirect_to dataset_path(@dataset.id)
    else
    end
  end

  private

  def generate_csv

  end

  def bulk_insert_tweets(tweets)
    ActiveRecord::Base.transaction do
      tweets.each do |t_info|
        t = Tweet.new(
          dataset: @dataset,
          text: t_info['text'],
          twitter_id: t_info['id']
        )
        t.save
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!

  def home
    if current_user and current_user.has_role? :admin
      @users_awaiting_approval = User.where(approved: false)
      @users_awaiting_approval = nil if @users_awaiting_approval == []
    end
  end

  def project
  end

  def instructions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def approve
    if current_user and current_user.has_role? :admin
      user = User.find(params[:id])
      user.approved = true
      user.save!
    end
    redirect_to :root
  end

  def make_admin
    user = User.find(params[:id])
    user.add_role :admin
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/datasets/edit.html.erb
<% content_for :title do %>dataset | annotate<% end %>
<% content_for :dataset_active do %>active<% end %>

<div class="row">
  <h2>Annotate for dataset <strong><%= @dataset.id%></strong></h2>
</div>
<div class="row">
  <%= button_to('Show Dataset', dataset_path(@dataset.id), :method => :get, class: "btn btn-success") %>
</div>

</br>

<% if @tweet and @tweet.errors.any? %>
<div class="alert alert-error">
  <button class="close" data-dismiss="alert"></button>
  <ul>
    <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="row">
  <div class="jumbotron">
  <p class="lead"><%= @tweet.text %></p>
  <a href="https://twitter.com/any/status/<%= @tweet.twitter_id %>" target="_blank" class="btn btn-primary btn-sm" role="button">View on Twitter</a>
  </br></br>
  <div class="row">
    <div class="col-xs-3">
      <%= form_for @dataset, url: dataset_path(@dataset.id) do |form| %>
        <%= hidden_field(:dataset, :tweet_id, value: @tweet.id) %>
        <%= hidden_field(:dataset, :annotation, value: 0) %>
        <%= button_tag(type: "submit", class: "btn btn-primary btn-lg button-annotate") do %>
          <%= image_tag("irrelevant.png", size: "50x50", class:"square-annotate-img") %>
          </br>
          <span class="span-annotate">Irrelevant</span>
        <% end %>
      <% end %>
    </div>
    <div class="col-xs-3">
      <%= form_for @dataset, url: dataset_path(@dataset.id) do |form| %>
        <%= hidden_field(:dataset, :tweet_id, value: @tweet.id) %>
        <%= hidden_field(:dataset, :annotation, value: 1) %>
        <%= button_tag(type: "submit", class: "btn btn-primary btn-lg button-annotate") do %>
          <%= image_tag("request.png", size: "55x50", class:"not-square-annotate-img") %>
          </br>
          <span class="span-annotate">Request</span>
        <% end %>
      <% end %>
    </div>
    <div class="col-xs-3">
      <%= form_for @dataset, url: dataset_path(@dataset.id) do |form| %>
        <%= hidden_field(:dataset, :tweet_id, value: @tweet.id) %>
        <%= hidden_field(:dataset, :annotation, value: 2) %>
        <%= button_tag(type: "submit", class: "btn btn-primary btn-lg button-annotate") do %>
          <%= image_tag("offer.png", size: "55x50", class:"not-square-annotate-img") %>
          </br>
          <span class="span-annotate">Offer</span>
        <% end %>
      <% end %>
    </div>
    <div class="col-xs-3">
      <%= link_to(edit_dataset_path(@dataset.id), :method => :get, class: "btn btn-primary btn-lg button-annotate") do %>
        <%= image_tag("doubt.png", size: "50x50", class:"square-annotate-img") %>
        </br>
        <span class="span-annotate">Not sure</span>
      <% end %>
    </div>
  </div>
</div>

app/views/datasets/index.html.erb
<% content_for :title do %>dataset | index<% end %>
<% content_for :dataset_active do %>active<% end %>
<h2>Datasets</h2>

<%= link_to "Export all annotated tweets", download_all_path, :method =>  :get,  class:"btn btn-success" %>
</br></br>
<div class="jumbotron">
  <div class="table-responsive " >
    <table class="table button-table table-hover" width="100%">
    <thead>
      <td>Id</td>
      <td>Created at</td>
      <td>Last update</td>
      <td>Tweets</td>
      <td>Annotated</td>
      <td>Owner</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </thead>
    <tbody>
      <% @datasets.order(updated_at: :DESC).each do |d| %>
      <% ready = d.tweets.size == d.annotated_tweets.size %>
      <tr>
        <td><%= d.id %></td>
        <td><%= d.created_at.in_time_zone("Caracas").strftime('%F %R') %></td>
        <td><%= d.updated_at.in_time_zone("Caracas").strftime('%F %R') %></td>
        <td><%= d.tweets.count %></td>
        <td><%= d.annotated_tweets.size %></td>
        <td><%= d.user.email %></td>
        <td>
          <% if @winners.include? d.user.id %>
          <%= image_tag("crown.png", size: "40x40") %>
          <% end %>
        </td>
        <td><%= button_to('Annotate', edit_dataset_path(d.id), :method => :get, :disabled => ready, class:"btn btn-primary") %></td>
        <td><%= button_to('Show', dataset_path(d.id), :method => :get, class:"btn btn-success") %></td>
        <td><%= link_to "Export", download_path(d.id), :method =>  :get,  class:"btn btn-success" %></td>
        <td><%= button_to('Delete', dataset_path(d.id), :method => :delete,  data: { confirm: "Are you sure?" }, class:"btn btn-danger") %></td>
      </tr>
      <% end %>
      <tr>
        <td>Total</td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= @total_annotated %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/datasets/new.html.erb
<% content_for :title do %>dataset | new<% end %>
<% content_for :dataset_active do %>active<% end %>
<h2>Upload a dataset</h2>

<%= form_for @dataset do |f| %>
  <%= f.file_field :csv %>

  <p>Owner:</p>
  <% @available_users.each do |user| %>
    </br>
    <%= f.label :user, user.email %>
    <%= f.radio_button(:user, user.email ) %>
  <% end %>

  </br></br>
  <%= f.submit :Upload %>
<% end %>

app/views/datasets/show.html.erb
<% content_for :title do %>dataset | show<% end %>
<% content_for :dataset_active do %>active<% end %>
<h2>Dataset <strong><%= @dataset.id %></strong></h2>


<% ready = @dataset.tweets.size == @dataset.annotated_tweets.size %>
<% if ready %>
  <p>Tweets: <%= @dataset.tweets.length %></p><p><strong>All done, thanks!</strong></p>
<% else%>
  <p>Tweets: <%= @dataset.tweets.length %> (<%= @dataset.annotated_tweets.size %> annotated).</p>
<% end %>
<div class="row">
  <div class="col-md-1 col-xs-4">
    <%= button_to('Annotate', edit_dataset_path(@dataset.id), :method => :get, :disabled => ready, class: "btn btn-primary") %>
  </div>
  <div class="col-md-1 col-xs-4">
    <%= button_to('Delete', dataset_path(@dataset.id), :method => :delete, class:"btn btn-danger",  data: { confirm: "Are you sure?" }) %></td>
  </div>
</div>
</br>
<% if  @dataset.annotated_tweets.size  > 0 %>
<div class="jumbotron">
  <div class="table-responsive">
    <table class="table table-hover" width="100%">
      <thead>
        <tr>
          <td></td>
          <td>Annotation</td>
          <td>Updated at</td>
          <td>Text</td>
        </tr>
      </thead>
      <tbody>
        <% @dataset.annotated_tweets.order(updated_at: :DESC).each do |t| %>
        <tr>
          <td><%= form_for @dataset, url: dataset_path(@dataset.id) do |form| %>
          <%= hidden_field(:dataset, :tweet_id, value: t.id) %>
          <%= hidden_field(:dataset, :annotation, value: nil) %>
          <%= submit_tag("Reset", class:"btn btn-warning") %>
          <% end %></td>
          <td><p class="lead text-center"><%= t.readable_annotation.capitalize %></p></td>
          <td><%= t.updated_at.in_time_zone("Caracas").strftime('%F %R')%></td>
          <td><%= t.text %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Virtual Farmacy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= (yield :home_active) %>"><%= link_to('Home', root_path, :method => :get) %></td></li>
        <li class="<%= (yield :project_active) %>"><%= link_to('The project', project_path, :method => :get) %></li>
        <li class="<%= (yield :instr_active) %>"><%= link_to('Instructions', instructions_path, :method => :get) %></li>
        <li class="dropdown <%= (yield :dataset_active) %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Datasets<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to('View', datasets_path, :method => :get) %></li>
            <li><%= link_to('Create', new_dataset_path, :method => :get) %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to( current_user.email  + ' Log out', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/cosmo/bootstrap.min.css" type="text/css">
  <title><%= (yield :title).capitalize %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>

  <% if current_user %>
    <%= render partial: 'layouts/nav_bar' %>
    <div class="container">
      <%= yield %>
    </div>
  <% else %>
    <%= yield %>
  <% end %>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

app/views/static_pages/_project_text.html.erb
<p class="lead">So yeah, <a 
href="https://www.theguardian.com/world/2016/may/18/venezuelans-barter-for-leftover-medicine-as-economic-crisis-deepens" 
target="_blank">this is happening.</a></p>

<p class="text-justify">To help with the Venezuelan <strong>prescription drugs crisis</strong> I am building a non-profitable platform to connect people requesting prescription drugs with people who might have them for sale, trade or donation. Currently Twitter is the most widely used platform to find drugs, but it's inefficient since there are a lot of different hashtags and accounts used to publish availability/necessity and no one can read all Twitter.
</br></br>
My plan is to build a machine learning classifier to detect relevant tweets (starting from a API search for tweets from drug crisis known accounts and hashtags) and classify them as requesting drugs or offering drugs. Afterwards I will build a platform to connect the users via a website, email, SMS, tweets, anything! But first I need to train the machine learning algorithm.
</br></br>
If you’re interested in learning about the specifics of the project <%= mail_to "sofiabravo103@gmail.com" do %>email me<% end %> and I will explain the implementation details (as soon as I’m done tweaking it).</p>

<p class="lead">How can you help? There are a lot of ways.</p>

<ol class="text-justify">
  <li><strong>You can help with annotation</strong>. The algorithm needs a lot of annotated tweets to learn from. To help <%= link_to "request an account", new_registration_path(:user) %> and wait for admin approval, after that you will be assigned with a set of tweets for annotation. You then classify these tweets on the website following the instructions provided. </li>
  <li>One of the major improvements in classification would come from filtering tweets using a <strong>list of venezuelan known prescription drug names and active components</strong>. So you can distinguish from a tweet requesting a hot dog from a tweet requesting something relevant. I am having trouble finding a digital source of information for this, so if there is anything you can suggest I would appreciate it.</li>
  <li> If you have an <strong>advance knowledge in machine learning supervised classification of short documents</strong> <%= mail_to "sofiabravo103@gmail.com" do %>email me<% end %>, I could really use your input.</li>
  <li> If you find anything that needs fixing in this website please report the issue on <a href="https://github.com/sofiabravo103/virtualfarmacy-classifier/issues" target="_blank">Github</a> (typos and grammar/spelling mistakes included!).</li>
</ol>

app/views/static_pages/home.html.erb
<% content_for :title do %>Home<% end %>
<% content_for :home_active do %>active<% end %>

<% if @users_awaiting_approval %>
<h5> Hey admin! This users are awaiting approval</h5>
<table>
  <thead>
    <tr>
      <td>Email</td>
      <td>Added on</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @users_awaiting_approval.each do |user| %>
      <tr>
          <td><%= user.email %></td>
          <td><%= user.created_at.in_time_zone("Caracas").strftime('%F %R') %></td>
          <td><%= button_to('Approve', approve_path(user.id), :method => :put) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% if @approved_users %>
<h3>Approved users</h3>
<table>
  <thead>
    <tr>
      <td>Email</td>
      <td>Added on</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @approved_users.each do |user| %>
      <tr>
          <td><%= user.email %></td>
          <td><%= user.created_at.in_time_zone("Caracas").strftime('%F %R') %></td>
          <td><%= button_to('Make admin', make_admin_path(user.id), :method => :put) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/static_pages/instructions.html.erb
<% content_for :title do %>Instructions<% end %>
<% content_for :instr_active do %>active<% end %>

<p class="lead">First of all thanks for helping out! Remind me to buy you a beer sometime.</p>
<p>To start annotating tweets click on <strong>Datasets > view</strong> above, find the one assigned to you and click annotate.</p>
<!--   -->
<p class="text-justify">The instructions are simple: <strong>classify according to the intention of the tweet.</strong> It does not matter if the tweet is requesting hot dogs or a presidential referendum, if it requests something then classify it as requesting. Same for offering. You will find that often many tweets indicate a location in which you can find a certain drug. Again the intention is what matters, so these cases should be classified as offering. Finally when you find anything that either does not provide enough information to classify it or seems to relate to a completely different topic (such as news or thank you replies) then classify it as irrelevant. <strong>Do no be afraid to classify as irrelevant.</strong> It is a very important category. Be wary of making your decision based on key words only, for example <em>todo el mundo requiere medicinas hoy en dia</em>, would be an irrelevant tweet, regardless of the word <em>requiere</em> which would seem to be always associated with requesting. One more thing, <strong>if you make a mistake annotating you can reset that annotation</strong>, just look the tweet up in the show dataset button and click reset.</p>

<p class="text-justify"><strong>Important! </strong> For the moment there is no way to include <strong>images or outside links</strong> on the learning algorithms, so please make your classification based on the tweet's text only. You can check out the original tweet on twitter.com if you are not completly sure what the tweet means (venezuelans tweet weird stuff in weird ways), but if the intention of the tweet is only visible through an image or link then classify as irrelevant. It's ok to classify as requesting/offering if the intention is in the text but the name and specifications of the medicine are inside a picture. Remember that we just want the algorithms to learn to differentiate offering text from requesting text.</p>

<p class="text-justify"><strong>Special cases:</strong></p>
<ol>
  <li>Some tweets offer trading meds for something else (other meds, hot dogs, a presidential referendum, etc, it does not matter). In its core this is actually an offering, so annotate as such.</li>
  <li>Some tweets request help to spread the word such as <em>ayudanos a difundir</em>. This tweet might be considered as requesting something (help), but since it is a really common special case we can treat it an exception. Therefore any tweet whose text consists only of requesting help to spread te word should be annotated as irrelevant.</li>
  <li>Another common case is when a tweet is a propaganda info of some kind. For example to promote a doctor (<em>Anglica Jerez - Dermatlogo - Barcelona - Anzotegui https//t.co/YqAhXHvOD3</em>), or a website (<em>Otro buscador de medicamento #AltamenteRecomendado https//t.co/a2UJrP9yPc</em>). Some people think of these cases as offerings but it will be treated as an exception since they're really common and they do not interest us, so annotate as irrelevant.</li>
</ol>


<p class="text-justify">That's it, have fun! And please don't hesitate to ask when you're not sure how to classify. Again, venezuelans tweet weird stuff in weird ways.</p>

app/views/static_pages/project.html.erb
<% content_for :title do %>The project<% end %>
<% content_for :project_active do %>active<% end %>

<%= render 'static_pages/project_text' %>